### ISSUE TITLE
Katex fails to render math expressions from ChatGPT4.

### ISSUE THREAD

**Issue by haje01** [huggingface/chat-ui#1097] opened 2024-05-03 08:19 UTC
I am using Chat UI version 0.8.3 and ChatGPT version gpt-4-turbo-2024-04-09.

ChatGPT is outputting formula delimiters as `\[`, `\]`, `\(`, `\)` and katex in the current version of ChatUI is not rendering them correctly. Based on my experiments, katex renders only formulas with `$` delimiters correctly.

I did a quick test with the following prompts

```echo following text as is: \[ D_i \]``` <- Fail to render

```echo following text as is: $ D_i $``` <- Successful

Thank you in advance.

**Comment by nsarrazin** [comment] 2024-05-05 15:42
Thanks for bringing this up! 

I can reproduce the issue, but I'm not sure how we can tackle it. We use marked but I can't see [an option for delimiters](https://katex.org/docs/options.html) there. 👀 

Would be open to ideas on how to fix this

**Comment by haje01** [comment] 2024-07-01 03:55
I also couldn't find a Katex setting to change the delimiter, so I worked around it by appending the following text in the ChatGPT prompt

```
The formula starts and ends with $ as a separator.
```

If the answer from the ChatGPT is in non-Latin characters, such as CJK, for example, the following prompt would be useful.

```
Use $ as a delimiter at the beginning and end of the formula. Make sure to put a single space after the delimiter $ whenever it's followed by a non-Latin character, such as CJK 
```
I hope this helps.

**Comment by thorvaldur-arnar** [comment] 2024-10-02 15:45
There seems to be an extension for configuring delimiters: https://katex.org/docs/autorender

**Comment by haje01** [comment] 2024-11-08 02:24
Specifying the following system prompt for the ChatGPT model seems to resolve most issues with equation rendering: 
```
Indicate the start and end of inline equations with '$ ' and ' $', respectively. Use $$ to delimit the start and end of block equations.
```

**Comment by nsarrazin** [comment] 2024-11-22 12:18
@haje01 this should be fixed using the latest images, we support the native katex formatting of GPT4 now! let me know if it doesn't work and i'll reopen

**Closed by nsarrazin** 2024-11-22 12:18 UTC
Labels: bug, help wanted, front
