### ISSUE TITLE
please add the api features for chat-ui

### ISSUE THREAD

**Issue by Mahesh-nrg** [huggingface/chat-ui#391] opened 2023-08-09 12:59 UTC
, so that api calling feature can be used to get the responses to the queries, directly by using api feature

**Comment by nsarrazin** [comment] 2023-08-10 09:25
Hey! I think this is a duplicate of #307 so I'm gonna be closing this for now but let me know if I made a mistake.

**Closed by nsarrazin** 2023-08-10 09:25 UTC
