### ISSUE TITLE
Bug: Unexpected execution result on Firefox browser with Chat-UI ver. 0.3.0

### ISSUE THREAD

**Issue by leemgs** [huggingface/chat-ui#335] opened 2023-07-10 04:40 UTC
I recently installed the 0.3.0 version of the HF Chat-UI software. 
I then performed an evaluation using the **HuggingFaceH4/starchat-beta** model. 
At that time, I typed the question "_Could you tell me about the weather in Toyko City in Japan on July-10-2023_?" and ran it.

Unfortunately, the results varied between browsers. 
In the Firefox browser, the result is displayed normally. 
However, the following error occurs in the Chrome browser. 

* **Error message:** 
```
403 You don't have access to this conversation. 
If someone gave you this link, ask them to use the 'share' feature instead.
```

I was wondering if anyone else is experiencing the same issue, any comments are welcome.

**Comment by nsarrazin** [comment] 2023-07-10 12:30
I think the issue is that by using two browsers you create two different "users", did you try to open the conversation from one browser into the other?

**Comment by nsarrazin** [comment] 2023-09-11 09:32
Closing this for now, let me know if you need further help.

**Closed by nsarrazin** 2023-09-11 09:32 UTC
Labels: support
