### ISSUE TITLE
Getting Chat-ui to work in a Docker (Setting MongoDB)

### ISSUE THREAD

**Issue by grahama1970** [huggingface/chat-ui#874] opened 2024-02-25 21:02 UTC
Hi. 
I couldn't  run chat-ui b/c docker (logs) said it couldn't find mongodb...which is running as a docker on the same computer.

In .env.local, I needed to change localhost to the local IP of the computer

# MONGODB_URL=mongodb://localhost:27017          # Bad
MONGODB_URL=mongodb://192.168.XX.XX:27017    # Works!

This tripped me up--maybe it will help others

**Comment by johndpope** [comment] 2024-02-25 23:30
fyi - ip 0.0.0.0 has solved me troubles in the past.

**Comment by nsarrazin** [comment] 2024-02-28 16:14
Maybe using the `host` network mode would help with docker? https://docs.docker.com/network/drivers/host/ or if you're running mongo in a container too, make sure to expose the ports there.

Anyway, seems like the issue is fixed, so closing this :grin:

**Closed by nsarrazin** 2024-02-28 16:14 UTC
